### ISSUE TITLE
CONTRIBUTING.md 

### ISSUE THREAD

**Issue by mlinksva** [OpenChain-Project/Online-Self-Certification-Web-App#1]
It'd be nice if this project had a `CONTRIBUTING.md` file with guidance on what kinds of issues and pull requests will help the project, though lots of other info can go there to help new contributors get started, some examples linked in https://opensource.guide/starting-a-project/#writing-your-contributing-guidelines

I imagine one thing specific to the project to note might be how the app is developed with/for new versions of the specification (branch, configuration, both, other...). But maybe this is a separate issue.

cc @jeremiah who suggested on mailing list.

**Comment by goneall** [comment]
Thanks Jeremiah for the suggestion.  I just added a contributing.md file.

**Comment by goneall** [comment]
Hi Jeremiah and Mike,


I just added a contributing.md file to Online-Self-Certification-Web-App.  If you seen any improvements, feel free to submit a pull request ;)

 

On the question of new versions of the spec, the application is very database driven and I believe it will handle new versions of the spec without any application changes.

 

The basic design is as follows:

·         Each spec version gets a new “questionnaire version” in the database

·         A new questionnaire for a new spec version can be uploaded by anyone with admin permissions in the application (it is basically a CSV file)

·         Any new users will get the latest questionnaire version

·         If there is a user who is in progress filling out an older version, they can continue or choose to reset their answers which will take them to the latest version

·         If there is a user who has submitted already, they can recall their submission, reset to the latest, and resubmit

 

I realize that last bullet is not quite ideal – it would be better to let a user manage multiple versions, but I decided not to “over engineer” the solution and go with a simpler approach.

 

Let me know if you have any questions or feedback on the approach.

 

Gary

**Comment by mlinksva** [comment]
@goneall thanks and I think that makes sense. Is [`filldbquestions.sql`](https://github.com/OpenChain-Project/Online-Self-Certification-Web-App/blob/57a264df71fb85b3d773d23aa61babe5892b805e/resources/filldbquestions.sql) the "basically a CSV file" you're referring to above?

**Comment by goneall** [comment]
@mlinksva The file is related, but I'll attach the CSV header row that describes the format more precisely.

There is an admin screen that allows you to download the current questionnaire

 in this format which can then be edited and re-uploaded.

**Comment by theopenchainproject** [comment]
Hi Gary!

> On Apr 13, 2017, at 6:10, goneall <notifications@github.com> wrote:
> · If there is a user who has submitted already, they can recall their submission, reset to the latest, and resubmit
> I realize that last bullet is not quite ideal – it would be better to let a user manage multiple versions, but I decided not to “over engineer” the solution and go with a simpler approach.

I believe we can expect users to access Online Self-Certification for multiple versions of the Spec over time. At the moment I understand we do not support recording this but - moving forward - we can expect it to be an important potential feature. 

Wind River is a good example. When 1.2 is available Mark will surely Self-Certify. This should not invalidate or “vanish” his previous Self-Certification to 1.1. 

I would therefore propose that expansion of the Web App to include such versioning should probably be a major consideration for the next update cycle (May/June).

Regards

Shane


--
Shane Coughlan
OpenChain Program Manager
e: coughlan@linux.com            
p: +81 (0) 80 4035 8083                
w: www.openchainproject.org
