### ISSUE TITLE
Critical failure with Save or Save and Submit

### ISSUE THREAD

**Issue by shanecoughlan** [OpenChain-Project/Online-Self-Certification-Web-App#144]
Saving answers or saving and submitting are both throwing an error on the web app. This makes the questionnaire unusable for conformance or health checks.

<img width="1917" alt="Screen Shot 2019-04-26 at 10 28 11" src="https://user-images.githubusercontent.com/3616071/56778991-ed838e80-6813-11e9-810a-df27141bde8c.png">
<img width="1918" alt="Screen Shot 2019-04-26 at 10 29 05" src="https://user-images.githubusercontent.com/3616071/56778993-ee1c2500-6813-11e9-9d22-8080a959f9ce.png">

**Comment by goneall** [comment]
This is resolved.

The original problem was there was a duplicate question number 1.c (should have been 1.b) in the questionnaire.

The application does look for this, but the validation somehow did not stop the update.  Issue #145 was added to track this issue.

We can also validate when submitting the questionnaire to the website.  A separate issue was added to track this: https://github.com/OpenChain-Project/conformance-questionnaire/issues/27
