### ISSUE TITLE
Downloading Answers does not work

### ISSUE THREAD

**Issue by theopenchainproject** [OpenChain-Project/Online-Self-Certification-Web-App#147]
Downloading answers to a CSV file does not work. With no questions filled out or all questions filled out the resulting CSV is blank.
<img width="956" alt="Screen Shot 2019-05-22 at 14 42 16" src="https://user-images.githubusercontent.com/27284210/58149960-1460a380-7ca0-11e9-9e74-1a15c17f7928.png">
[openchain-answers.xlsx](https://github.com/OpenChain-Project/Online-Self-Certification-Web-App/files/3205769/openchain-answers.xlsx)

**Comment by goneall** [comment]
I was able to duplicate this problem so i should be able to fix it.  I'll take a look over the next couple of days.

**Comment by goneall** [comment]
Update: this only occurs in the production instance.  On my local development environment, it works fine.  I'll need to add some additional logging to figure this out.  It may take a few days to resolve.

**Comment by goneall** [comment]
Curiouser and curioser.  The production environment works for my admin login but doesn't work for my normal user login.  When I tried this on my development machine, the admin worked and the normal user did not work.  That was until I set some breakpoints to debug the problem.  Now it works for the normal user on my development environment.

I'll continue trying to debug.

**Comment by goneall** [comment]
The download answers only downloads answers after they are saved.

If you don't save the answers, it will not be reflected in the CSV.

The CSV also does not include any answers which are not answered.

This is actually working as designed, but the design has a couple of problems.

If you're just trying to download the survey using the download answers, you will only see survey questions.

The second problem is if there are answers when the survey is not saved, I would expect to see what I see on my screen and not what is stored on the computer.

I'm going to close this and open two enhancements:

- Issue #149 to warn users when downloading with unsaved answers
- Issue #150 to include unanswered questions in the download

I also found another issue when debugging.  If a user leaves the page without saving the questions, there is no warning.  i'll enter a new issue to track.

**Comment by shanecoughlan** [comment]
Thanks Gary! I commented in the new issues.
