### ISSUE TITLE
First instance of opening web app results in broken menu bar

### ISSUE THREAD

**Issue by theopenchainproject** [OpenChain-Project/Online-Self-Certification-Web-App#148]
The page needs to be refreshed to show sign-up and log-in options. This occurs on Safari and Chrome.
<img width="1055" alt="Screen Shot 2019-05-22 at 14 46 23" src="https://user-images.githubusercontent.com/27284210/58150127-a4065200-7ca0-11e9-80e6-0c2949c47f52.png">

**Comment by goneall** [comment]
@theopenchainproject I was not able to duplicate the problem.  I suspect this may be a browser caching issue.  This is supported by the fact that a refresh fixes the problem.  Can you see if you can duplicate the problem?  If it can not be duplicated and it is not reported by anyone else, I would suggest closing it.  If you can duplicate it, I'll need some of your time on a web conference to try to debug and find out what is happening.

**Comment by goneall** [comment]
I was able to duplicate this problem while testing out the registration failed.  On the registration failed page, the menus are missing.  This may be specific to certain pages or it may be a timing issue.

**Comment by goneall** [comment]
In reviewing the code, it looks like it is possible for the createNavMenu to be called before the elements it references are loaded:

```
	$("#topnav").load("topnav.html");
	$("#footer-outer").load('footer.html');
	createNavMenu();
```

This can be fixed by moving the createNavMenu into a callback function for the topnav loading.

**Comment by goneall** [comment]
@theopenchainproject let me know if you see this again with the updated software.

**Comment by shanecoughlan** [comment]
Seems to be working fine now! Thank you!
