### ISSUE TITLE
Add localization changes for recent code changes

### ISSUE THREAD

**Issue by goneall** [OpenChain-Project/Online-Self-Certification-Web-App#157]
As discussed in PR #146

**Comment by goneall** [comment]
@brandelune I didn't see the commits you referred to in PR #146.  

I merged all the outstanding PR's, so if you could create a new PR against the master branch.

@theopenchainproject  Once I have the PR, , I'll merge, test and deploy.

**Comment by brandelune** [comment]
Sorry, I forgot to click "create PR" last night... That should be good now.

**Comment by goneall** [comment]
Resolved by PR #159 and PR #158
