### ISSUE TITLE
Japanese version of the WebApp is broken (displays English instead)

### ISSUE THREAD

**Issue by shanecoughlan** [OpenChain-Project/Online-Self-Certification-Web-App#165]
We have a broken Japanese version of the WebApp. Selecting the languages displays English instead of Japanese as expected. 

This may be related to this pull request:
https://github.com/OpenChain-Project/Online-Self-Certification-Web-App/pull/163
However, cause currently unknown.

<img width="1505" alt="Screen Shot 2019-07-01 at 22 59 44" src="https://user-images.githubusercontent.com/3616071/60445488-42031a00-9c5a-11e9-8eee-5e22bc2e91f7.png">

**Comment by goneall** [comment]
Fixed with PR #166
