### ISSUE TITLE
Change the button from "Select Version" to "Change Version" to make it clearer

### ISSUE THREAD

**Issue by shanecoughlan** [OpenChain-Project/Online-Self-Certification-Web-App#176]
<img width="1181" alt="Select Version to Change Version" src="https://user-images.githubusercontent.com/3616071/89294909-1fcc9e80-d69b-11ea-812b-41408226af37.png">

**Comment by goneall** [comment]
Following are the files/lines that need to be updated:

* https://github.com/OpenChain-Project/Online-Self-Certification-Web-App/blob/e9a9e8e39a874ed63bc805fc4754f09d6100d4b5/WebContent/resources/locales/en/translation.json#L169
* https://github.com/OpenChain-Project/Online-Self-Certification-Web-App/blob/e9a9e8e39a874ed63bc805fc4754f09d6100d4b5/WebContent/resources/locales/ja/translation.json#L169
* https://github.com/OpenChain-Project/Online-Self-Certification-Web-App/blob/e9a9e8e39a874ed63bc805fc4754f09d6100d4b5/WebContent/resources/locales/ko/translation.json#L169

**Comment by goneall** [comment]
@shanecoughlan Back to you to update the text

**Comment by shanecoughlan** [comment]
Thanks Gary. Japanese and Korean are already optimal. English has been updated in a new branch with a pull request for merge to main at:
https://github.com/OpenChain-Project/Online-Self-Certification-Web-App/pull/177
