### ISSUE TITLE
Add translation for Japanese "Yes"

### ISSUE THREAD

**Issue by goneall** [OpenChain-Project/Online-Self-Certification-Web-App#188]
The questionnaire response for Japanese Yes is currently showing in English

The following line needs to be updated:

https://github.com/OpenChain-Project/Online-Self-Certification-Web-App/blob/43f3b1859e76cf839d1e9b9242184690be645290/WebContent/resources/locales/ja/translation.json#L174

**Comment by goneall** [comment]
Shane emailed me the translation: はい

I'll include this in the next application update.

**Comment by brandelune** [comment]
I've already added it to 2.1.1 on my side.

**Comment by goneall** [comment]
Thanks @brandelune

**Comment by goneall** [comment]
Resolved by PR #202
