### ISSUE TITLE
Additional languages

### ISSUE THREAD

**Issue by goneall** [OpenChain-Project/Online-Self-Certification-Web-App#194]
Additional languages are planned to be added through the month of December 2020.

For each language, the following needs to be updated:

1. Verify that the new language is included in all of the translation.json files in the [front-end locales folder](https://github.com/OpenChain-Project/Online-Self-Certification-Web-App/tree/master/WebContent/resources/locales).  For example, if adding Korean, the Japanese translations needs to include the line `"Korean":"韓国語 (ko)"`
2. The languages array in globals.js needs to be updated to include the new languages: https://github.com/OpenChain-Project/Online-Self-Certification-Web-App/blob/43f3b1859e76cf839d1e9b9242184690be645290/WebContent/resources/global.js#L24  Note that the language needs to match exactly the text in the translations used in step 2 above.

**Comment by goneall** [comment]
@brandelune If you could take care of 1-3 above in one or more pull requests, I'll take care of 4.

BTW - when I went and looked at the existing translations, most of the languages were already present for step 2 above - but we still should verify.  We missed Korean in our last rollout which didn't show up translated.

**Comment by goneall** [comment]
@brandelune I updated the tasks above to reflect the fact we are not localizing the app (sorry for the confusion).

The only thing that I need to prepare for the languages is to verify the translations already exist for the translations we currently support (item 1 above).

It looks like this may already be taken care of depending on which language your using.

Let me know if any updates or needed - or let me know the planned languages, and I'll check.

**Comment by brandelune** [comment]
I'm only seeing item 1 and 2. I'll be getting the files later today. If you can clarify what item 3 is I'll handle it.

**Comment by goneall** [comment]
@brandelune - Sorry for the confusion, I updated the issue once I realized we were only localizing the questionnaire - not the entire website.

**Comment by brandelune** [comment]
Gary, here is a csv blob for the 11 languages in the 6 primary languages (5+english). The remaining language versions will come on the 17th.

en,ja,zh-zh,zh-tw,de,ko
English,英語,英文,英語,Englisch,영어
Simplified Chinese,簡体字,简体字,中文簡體,Vereinfachtes Chinesisch,간체
Traditional Chinese,繁体字,繁体字,中文繁體,Traditionelles Chinesisch,번체
Korean,韓国語,韩文,韓語,Koreanisch,한국어
Japanese,日本語,日文,日語,Japanisch,일본어
German,ドイツ語,德文,德語,Deutsch,독일어
French,フランス語,法文,法語,Französisch,프랑스어
Italian,イタリア語,意大利文,義大利語,Italienisch,이태리어
Spanish,スペイン語,西班牙文,西班牙語,Spanisch,스페인어
Hindi,ヒンジ語,印地文,北印度語,Hindi,힌지어
Russian,ロシア語,俄文,俄語,Russisch,러시아어
Hebrew,ヘブライ語,希伯来文,希伯來語,Hebräisch,히브리어

**Comment by goneall** [comment]
@brandelune Thanks for the language translations - this should work.  I'll update the app tomorrow.

**Comment by goneall** [comment]
Added PR #201 with the additional terms.

**Comment by goneall** [comment]
Resolved with PR #201
