### ISSUE TITLE
Missing icon files

### ISSUE THREAD

**Issue by goneall** [OpenChain-Project/Online-Self-Certification-Web-App#20]
I'm not sure if this is an issue, but the server logs are showing the following 404 errors:

127.0.0.1 - - [06/Feb/2018:23:46:46 +0000] "GET /apple-touch-icon-precomposed.png HTTP/1.1" 404 1015
127.0.0.1 - - [06/Feb/2018:23:46:46 +0000] "GET /apple-touch-icon.png HTTP/1.1" 404 991
127.0.0.1 - - [06/Feb/2018:23:46:46 +0000] "GET /favicon.ico HTTP/1.1" 404 973
127.0.0.1 - - [06/Feb/2018:23:46:46 +0000] "GET /apple-touch-icon-precomposed.png HTTP/1.1" 404 1015
127.0.0.1 - - [06/Feb/2018:23:46:46 +0000] "GET /apple-touch-icon.png HTTP/1.1" 404 991
127.0.0.1 - - [06/Feb/2018:23:46:46 +0000] "GET /favicon.ico HTTP/1.1" 404 973

**Comment by theopenchainproject** [comment]
Does this apply to our new app?

**Comment by goneall** [comment]
These are no longer showing up in the log,s it looks like the new app fixed this :)
