### ISSUE TITLE
Consistent use of open source

### ISSUE THREAD

**Issue by goneall** [OpenChain-Project/Online-Self-Certification-Web-App#33]
Replace each incident of “FOSS” or “Free Software” or “Free and Open Source Software” or “Open Source” (capitalized) by “open source” to be consistent with the specification.

**Comment by goneall** [comment]
I did a search of the code base and found only one occurrence of FOSS:  https://github.com/OpenChain-Project/Online-Self-Certification-Web-App/blob/31b6e049b2cde23813ee15a4ff2b7d1ee4837f68/WebContent/index.html#L39

Please change `The OpenChain Specification represents a core set of requirements a quality FOSS compliance program must satisfy. It fosters efficient and effective compliance of open source licenses across the supply chain. By self-certifying, participants are able to confirm they are in compliance with the Specification’s requirements.` 

to:

`The OpenChain Specification represents a core set of requirements a quality open source compliance program must satisfy. It fosters efficient and effective compliance of open source licenses across the supply chain. By self-certifying, participants are able to confirm they are in compliance with the Specification’s requirements.`

**Comment by openchain-visolve** [comment]
Issue Resolved and Code changes has been committed to html_internationalization  branch. Please check and share your views.

**Comment by shanecoughlan** [comment]
There is still text in the site using "FOSS". Please ensure all incidents of FOSS, Open Source (capitalized) and other items like OSS or FLOSS are changed to:
(1) open source (uncapitalized inside sentences)
(2) Open source (first letter capitalized when starting sentences)

<img width="1518" alt="screen shot 2019-01-16 at 16 19 05 copy" src="https://user-images.githubusercontent.com/3616071/51232996-ff030200-19ab-11e9-8b5b-9392fba0baee.png">

**Comment by goneall** [comment]
The FOSS text is in the questionnaire data which has it's own issue and pull request: https://github.com/OpenChain-Project/conformance-questionnaire/pull/10

Closing this issue as a duplicate.
