### ISSUE TITLE
Attempting to access page directly does not redirect to login

### ISSUE THREAD

**Issue by goneall** [OpenChain-Project/Online-Self-Certification-Web-App#37]
Accessing any page directly without being logged in should redirect to the login page.

For example: http://openchain-env.m6rqmtrixp.us-west-1.elasticbeanstalk.com/admin.html

Following the above link should redirect.

**Comment by openchain-visolve** [comment]
Attempting to access unauthorized files without logged in has been redirected to login page.
Code changes has been committed to responsive_ui_i18n branch. Please check and share your views.

**Comment by goneall** [comment]
Resolved on the i18n branch
