### ISSUE TITLE
Update notice file with new packages added for the responsive UI and I18N

### ISSUE THREAD

**Issue by goneall** [OpenChain-Project/Online-Self-Certification-Web-App#42]
The NOTICE file includes all embedded software and their licenses.  Several new packages were added to the JavaScript libraries for the responsive UI and I18N extensions.  The Notice file needs to be updated to reflect these new additions.

**Comment by openchain-visolve** [comment]
We added the library files (DataTables & I18N) and Code changes has been committed to responsive_ui_i18n branch.

**Comment by goneall** [comment]
Resolved on the I18n branch
