### ISSUE TITLE
Add a link to the conformance checklist PDF document

### ISSUE THREAD

**Issue by goneall** [OpenChain-Project/Online-Self-Certification-Web-App#43]
Add a link "Conformance Checklist" which links to https://openchain-project.github.io/conformance-questionnaire/questionnaire.pdf

If another language is selected, the "questionnaire.pdf" would be "questionnaire-XX.pdf" where XX is the locale.  We could dynamically change the link depending on the language choosen.

Note: Although it is unlikely we would have languages in the dropdown which do not have a corresponding PDF language, it would be nice to fall back to the default language questionnaire if the PDF document does not exist.

**Comment by goneall** [comment]
The link can be at the bottom of the index.html page.  Just a single line:

`You can download a PDF version of the conformance questionnaire <a href=xxx>here</a>.`

**Comment by shanecoughlan** [comment]
Yes, that would work.

Perhaps we can use slightly different wording:

Do you prefer to work with a printed checklist? You can download the offline conformance handbook <a href=xxx>here</a>.

**Comment by goneall** [comment]
Agree with Shane's wording.

@openchain-visolve please add this to the next update.

**Comment by goneall** [comment]
Link was added, however there is an issue with the link.  Opened a new issue #80
