### ISSUE TITLE
Missing bullet point for Getting Started front page list

### ISSUE THREAD

**Issue by swinslow** [OpenChain-Project/Online-Self-Certification-Web-App#44]
Minor nit -- when I visit the front page in Firefox on a Mac, there are six items listed under "Getting Started". However, the final item on the list ("Archive a Reference Copy of...") does not have a bullet point, while the first five items on the list do have bullet points.

It looks like the HTML tag for that list item was accidentally set as `liv` rather than `li`.

**Comment by openchain-visolve** [comment]
Issue Resolved and Code changes has been committed to html_internationalization  branch. Please check and share your views.
