### ISSUE TITLE
Can not login using Firefox

### ISSUE THREAD

**Issue by goneall** [OpenChain-Project/Online-Self-Certification-Web-App#45]
Attempting to login using Firefox browser redirects to the login screen with the username and password passed as query parameters.  This is preventing users from logging in.

Note: we probably should not pass the password as an unencrypted string in a query parameter.

The same issue does not occur on the production application.

FIrefox version 61.0.1 64 bit windows.

@swinslow also hit this issue using Firefox on a mac.

**Comment by openchain-visolve** [comment]
We fixed the issue and code  changes has been committed  under html_internationalization branch. Please check and share share your views
