### ISSUE TITLE
Extra parenthesis on Survey.html page

### ISSUE THREAD

**Issue by goneall** [OpenChain-Project/Online-Self-Certification-Web-App#48]
Title of the page currently shows `(Survey Version 1.3 (Survey Version 1.3.0)`.  The leading parenthesis should be removed: `Survey Version 1.3 (Survey Version 1.3.0)`

**Comment by goneall** [comment]
The most recent fix moved the parenthesis, but there is still an extra parenthesis:

`Specification Version 1.3 ((Survey Version 1.3.0)`

**Comment by openchain-visolve** [comment]
Extra character was removed and Code changes has been committed. Please check and share your views.

**Comment by shanecoughlan** [comment]
It still says "(Survey Version 1.3 (Survey Version 1.3.0)"

Merge into Issue #64 for fix.

**Comment by goneall** [comment]
Fixed in the latest version
