### ISSUE TITLE
Logo need white background or to be changed into white backgroud

### ISSUE THREAD

**Issue by shanecoughlan** [OpenChain-Project/Online-Self-Certification-Web-App#52]
[
![5fc13816-a12d-4a57-8583-2c96c5db5a29](https://user-images.githubusercontent.com/3616071/51227770-1f759100-1999-11e9-8457-749e8bb49f26.png)
](url)

The OpenChain logo is should have a white background. The background on the web app is black at the logo location.

**Comment by goneall** [comment]
@shanecoughlan Do we want to change the background color of the entire menu bar or just have a white box behind the logo?

**Comment by theopenchainproject** [comment]
Hi @goneall, I have created a version of the logo with a white background for the web app.
![long-logo-rounded-white-background](https://user-images.githubusercontent.com/27284210/51309297-693ca500-1a87-11e9-9a95-c0f32c16d9dd.png)

**Comment by goneall** [comment]
@shanecoughlan Thanks for the logo

@openchain-visolve Let's go ahead and place the new logo in the menu

**Comment by goneall** [comment]
PR #80 still has the old transparent logo

**Comment by goneall** [comment]
@shanecoughlan Can you review the logo - we can increase the size if you would like.  Note: you need to clear the browser cache to get the latest image:  http://openchain-env.m6rqmtrixp.us-west-1.elasticbeanstalk.com/

**Comment by goneall** [comment]
Fixed with PR #83

**Comment by theopenchainproject** [comment]
Hi Gary! The logo on the web app is currently the full size (8000+ px with 300 px resolution) and it takes ages to download. Suggest using an optimized version as attached. 

Regarding visual size on the web app, it works fine.
![logo_openchain](https://user-images.githubusercontent.com/27284210/51650772-e195ef80-1fcc-11e9-93e7-96a57d9829c6.png)

**Comment by goneall** [comment]
@openchain-visolve Can you replace the logo in your next PR?

**Comment by goneall** [comment]
The logo has been replaced with PR #87
