### ISSUE TITLE
The menu “burger” does not expand on iOS 12

### ISSUE THREAD

**Issue by shanecoughlan** [OpenChain-Project/Online-Self-Certification-Web-App#53]
iPhone X with iOS 12 cannot expand menu “burger” to access pages beyond the homepage in both portrait and landscape mode.

![c82c2d77-93c4-4429-b4bf-629d45425711](https://user-images.githubusercontent.com/3616071/51227904-b2aec680-1999-11e9-96c4-b0bc1d8b64e5.png)
![432ecaa4-d3d1-4a28-b94a-3885d7b32c7e](https://user-images.githubusercontent.com/3616071/51227906-b3475d00-1999-11e9-89c4-169bd103e5c0.png)

**Comment by theopenchainproject** [comment]
Fix works. Closing!
