### ISSUE TITLE
Spacing is off on part of the sign-up page

### ISSUE THREAD

**Issue by shanecoughlan** [OpenChain-Project/Online-Self-Certification-Web-App#54]
<img width="1250" alt="screen shot 2019-01-16 at 15 50 17" src="https://user-images.githubusercontent.com/3616071/51231360-9ebd9180-19a6-11e9-8db5-fc6da8ad4e2d.png">

Spacing issue as highlighted between the two items.

**Comment by goneall** [comment]
Fixed with PR #83
