### ISSUE TITLE
Formatting adjustments to conforming entities list

### ISSUE THREAD

**Issue by shanecoughlan** [OpenChain-Project/Online-Self-Certification-Web-App#55]
<img width="1531" alt="screen shot 2019-01-16 at 15 52 37" src="https://user-images.githubusercontent.com/3616071/51231449-e6441d80-19a6-11e9-8e03-1b50fc48ce72.png">

The search text should be to the left of the search box (or ideally inside it)

The text showing number of entries should be moved to the right.

**Comment by goneall** [comment]
Resolved in PR #80
