### ISSUE TITLE
Text reduction on primary admin page

### ISSUE THREAD

**Issue by shanecoughlan** [OpenChain-Project/Online-Self-Certification-Web-App#56]
<img width="1517" alt="screen shot 2019-01-16 at 15 55 10" src="https://user-images.githubusercontent.com/3616071/51231553-3e7b1f80-19a7-11e9-84cc-ef1d416123b0.png">

Awaiting Approval and Rejected do not need "Submitted" prefix

**Comment by goneall** [comment]
Fixed on the I18N branch
