### ISSUE TITLE
Admin page "Manage Survey Content" needs review - Button Alignment

### ISSUE THREAD

**Issue by shanecoughlan** [OpenChain-Project/Online-Self-Certification-Web-App#60]
<img width="1165" alt="screen shot 2019-01-16 at 15 57 19" src="https://user-images.githubusercontent.com/3616071/51232331-a7fc2d80-19a9-11e9-8d58-608aea4d10f9.png">

The "Update Survey Questions" button is centered rather than right-aligned as per the rest of the site

Related to #58 and #59

**Comment by shanecoughlan** [comment]
Location: http://openchain-env.m6rqmtrixp.us-west-1.elasticbeanstalk.com/admin.html

**Comment by goneall** [comment]
Fixed on the I18N branch
