### ISSUE TITLE
Admin page "Site Status" needs review - Placement

### ISSUE THREAD

**Issue by shanecoughlan** [OpenChain-Project/Online-Self-Certification-Web-App#61]
<img width="1165" alt="screen shot 2019-01-16 at 15 57 19" src="https://user-images.githubusercontent.com/3616071/51232367-c95d1980-19a9-11e9-8eb4-19a072b6377a.png">

The "Site Status" Section is the first item you see when you open the admin page. It will not be used frequently and should be located at the bottom of the page.

**Comment by shanecoughlan** [comment]
Location: http://openchain-env.m6rqmtrixp.us-west-1.elasticbeanstalk.com/admin.html

**Comment by goneall** [comment]
Fixed on the I18N branch
