### ISSUE TITLE
Admin page "Manage Survey Content" needs review - Placement

### ISSUE THREAD

**Issue by shanecoughlan** [OpenChain-Project/Online-Self-Certification-Web-App#62]
<img width="1165" alt="screen shot 2019-01-16 at 15 57 19" src="https://user-images.githubusercontent.com/3616071/51232404-ef82b980-19a9-11e9-9de1-46dd0d2724c9.png">

This is the second item on the page when opened, but will be used far less than items like "Awaiting Approval"

It should be moved to second last on the site, just before "Site Status" as per Issue #61

Related to #58, #59, #60 

http://openchain-env.m6rqmtrixp.us-west-1.elasticbeanstalk.com/admin.html

**Comment by goneall** [comment]
Fixed on the I18N branch
