### ISSUE TITLE
Self Certification Page - Confusing Title Text

### ISSUE THREAD

**Issue by shanecoughlan** [OpenChain-Project/Online-Self-Certification-Web-App#63]
<img width="1518" alt="screen shot 2019-01-16 at 16 19 05 copy 2" src="https://user-images.githubusercontent.com/3616071/51232606-b1d26080-19aa-11e9-8563-cdcfe24de1a3.png">

The OpenChain Specification review is not a survey, it is a questionnaire.

**Comment by shanecoughlan** [comment]
Location http://openchain-env.m6rqmtrixp.us-west-1.elasticbeanstalk.com/survey.html

**Comment by goneall** [comment]
Please change "OpenChain Self Certification Survey" to "OpenChain Self Certification Questionnaire" and "(Survey Version 1.3.0)" to "(Questionnaire Version 1.3.0)"

**Comment by goneall** [comment]
Related to issue #64

**Comment by goneall** [comment]
Resolved in PR #80  Some other references to Survey in the app.  A separate issue #78 is opened to track these additional occurrences.
