### ISSUE TITLE
Self Certification Page - Confusing Version Number Text

### ISSUE THREAD

**Issue by shanecoughlan** [OpenChain-Project/Online-Self-Certification-Web-App#64]
<img width="1518" alt="screen shot 2019-01-16 at 16 19 05" src="https://user-images.githubusercontent.com/3616071/51232643-d29ab600-19aa-11e9-9673-c781b4c37411.png">

The current text appears to be autogenerated and is confusing. It should be:
(1) Centered to match title
(2) Read "Version X.X of the OpenChain Specification"

Location http://openchain-env.m6rqmtrixp.us-west-1.elasticbeanstalk.com/survey.html

Related to Issue #63

**Comment by goneall** [comment]
There is a version of the specification and a separate version for the questionnaire.  We have several instances where we update the questionnaire between revisions of the specification.  We could hide the questionnaire version to reduce confusion, but I feel it may be useful information in some circumstances.

**Comment by goneall** [comment]
Text has been updated to `Specification Version 1.3 (Survey Version 1.3.0)`  This fix will be available in the next update of the application.

**Comment by shanecoughlan** [comment]
Hi Gary

The text on the life instance still reads "(Survey Version 1.3 (Survey Version 1.3.0)"

I understand that the questionnaire version may be useful in some circumstances but these will be in the minority and primarily for administration or power users. I have a preference for making sure the average user has the simplest possible interface. From my experience "Specification Version 1.3 (Survey Version 1.3.0)" will lead to questions about which survey version people need and reduce the likelihood of a successful engagement. I still believe it should read "Version X.X of the OpenChain Specification"

If the survey version is required then I suggest we split it away from this section and have it located at the bottom of the page with the text "This is the online self-certification for Version X.X of the OpenChain Specification using Version 1.3.0 of our questionnaire."

**Comment by goneall** [comment]
@shanecoughlan There are to cases where the questionnaire version (a.k.a. survey version) would be useful:

1. Reporting issues related to the questionnaire
2. Verifying the correct version of the questionnaire has been uploaded (only used by administrators)

Based on this, I suggest moving the questionnaire version to the bottom of the page, perhaps in smaller type.

**Comment by goneall** [comment]
@shanecoughlan How is this for a proposed page layout?

![questionnaire page](https://user-images.githubusercontent.com/378172/51340788-b9dede80-1a44-11e9-9dc7-fb87a5e273d5.png)

**Comment by theopenchainproject** [comment]
Perfect! Suggest we center it though :)

**Comment by theopenchainproject** [comment]
Reviewing latest app version: suggest we delete the "Site Status" as redundant. 
<img width="816" alt="screen shot 2019-01-21 at 16 42 31" src="https://user-images.githubusercontent.com/27284210/51459372-af517b80-1d9b-11e9-94f6-a630553d2d19.png">

**Comment by goneall** [comment]
Resolved in PR #80
