### ISSUE TITLE
Self Certification Page - Confusing Section Title Text

### ISSUE THREAD

**Issue by shanecoughlan** [OpenChain-Project/Online-Self-Certification-Web-App#66]
<img width="1518" alt="screen shot 2019-01-16 at 16 19 05 copy" src="https://user-images.githubusercontent.com/3616071/51232907-bcd9c080-19ab-11e9-8ca6-33e948bd5105.png">

The Section titles are confusing with text like "G1: G1: Know Your FOSS Responsibilities"

This should be changed to "Know Your FOSS Responsibilities"

Related to #63 and #64

Location http://openchain-env.m6rqmtrixp.us-west-1.elasticbeanstalk.com/survey.html

**Comment by goneall** [comment]
The leading section "G1" has been removed and will be available next time we update the site.

The second "G1" is in the conformance-questionnaire repo.  We would need to remove the G1 from each of those sections.

Personally, I like the format "G1: Know your FOSS responsibilities" as it gives you a section reference you can use to refer back to the specification.

**Comment by goneall** [comment]
The web application has been fixed to remove the leading G1.

If we want to change the section titles to not include the section numbers, please open an issue in the conformance questionnaire repo.
