### ISSUE TITLE
OpenChain Self Certification Questionnaire - Spacing Issues

### ISSUE THREAD

**Issue by shanecoughlan** [OpenChain-Project/Online-Self-Certification-Web-App#67]
<img width="1480" alt="screen shot 2019-01-16 at 16 30 35" src="https://user-images.githubusercontent.com/3616071/51233074-3bcef900-19ac-11e9-89c4-3f1aaf33e5fd.png">

There are spacing issues with the self certification questionnaire, different spacing between the yes/no text and the question text. It should all be the latter for clarity:
http://openchain-env.m6rqmtrixp.us-west-1.elasticbeanstalk.com/survey.html

**Comment by goneall** [comment]
Fixed on the I18N branch
