### ISSUE TITLE
OpenChain Self Certification Questionnaire - Open vs Closed on open

### ISSUE THREAD

**Issue by shanecoughlan** [OpenChain-Project/Online-Self-Certification-Web-App#69]
<img width="1334" alt="screen shot 2019-01-16 at 16 38 32" src="https://user-images.githubusercontent.com/3616071/51233615-a3d20f00-19ad-11e9-903e-f4ace84b321a.png">
<img width="1271" alt="screen shot 2019-01-16 at 16 38 42" src="https://user-images.githubusercontent.com/3616071/51233619-a5033c00-19ad-11e9-9e7d-1d3754959aee.png">

The questionnaire opens with Section 1 fully expanded, but this text is lengthy. It should probably open with the sections closed to allow users to quickly see all the options.

**Comment by goneall** [comment]
Fixed on the I18N branch
