### ISSUE TITLE
OpenChain Self Certification Questionnaire - Weird legacy text top right

### ISSUE THREAD

**Issue by shanecoughlan** [OpenChain-Project/Online-Self-Certification-Web-App#71]
<img width="1368" alt="screen shot 2019-01-16 at 16 39 30" src="https://user-images.githubusercontent.com/3616071/51233698-e693e700-19ad-11e9-95ca-02e8fc23c2c0.png">

There is an error on the page with the letter "F" appearing on the top right. Code issue.

**Comment by goneall** [comment]
Fixed on the I18N branch
