### ISSUE TITLE
Language switching should follow LF norm or otherwise be easier to recognize 

### ISSUE THREAD

**Issue by shanecoughlan** [OpenChain-Project/Online-Self-Certification-Web-App#72]
The current language switcher is different to the one used by LF. 
<img width="1521" alt="screen shot 2019-01-16 at 16 39 39" src="https://user-images.githubusercontent.com/3616071/51233750-0aefc380-19ae-11e9-9bf6-0be9122b681a.png">

We should try to find a solution that splits the difference, particularly with regards readability and familiarity. 

Perhaps it should just be text saying "Language"

**Comment by goneall** [comment]
The language switcher was modeled after the CII best practices web page.  Should we be compatible with CII or with the main LF banner?  On concern on the LF approach is that there is not much room if several languages are involved.

![image](https://user-images.githubusercontent.com/378172/51266861-343e2e80-1971-11e9-9af6-9aeb693185d7.png)

**Comment by goneall** [comment]
@shanecoughlan - Let me know if you are OK with the CII language chooser style or if you feel we should switch to the LF standard version.

**Comment by theopenchainproject** [comment]
Hi Gary. Great points. Let's use the CII Best Practices method. Therefore no change needed.
