### ISSUE TITLE
Menu bar formatting is out of alignment + text size issues

### ISSUE THREAD

**Issue by shanecoughlan** [OpenChain-Project/Online-Self-Certification-Web-App#73]
<img width="1425" alt="screen shot 2019-01-16 at 16 48 33" src="https://user-images.githubusercontent.com/3616071/51233952-b26cf600-19ae-11e9-9a67-4d82f2b11cbc.png">

The "Admin" and "Account" items have different alignment and text sizes

**Comment by goneall** [comment]
Fixed on the I18N branch
