### ISSUE TITLE
Reviewing latest Admin page: suggest we delete the "Site Status" as redundant.

### ISSUE THREAD

**Issue by theopenchainproject** [OpenChain-Project/Online-Self-Certification-Web-App#75]
Reviewing latest app version: suggest we delete the "Site Status" as redundant. 
<img width="816" alt="screen shot 2019-01-21 at 16 42 31" src="https://user-images.githubusercontent.com/27284210/51459372-af517b80-1d9b-11e9-94f6-a630553d2d19.png">

_Originally posted by @theopenchainproject in https://github.com/OpenChain-Project/Online-Self-Certification-Web-App/issues/64#issuecomment-455976263_

**Comment by goneall** [comment]
Fixed with PR #83
