### ISSUE TITLE
Add support for multiple spec versions per organization

### ISSUE THREAD

**Issue by goneall** [OpenChain-Project/Online-Self-Certification-Web-App#9]
Currently, one organization can only submit a certification request for one version of the openchain spec at one time.  To move to a more recent version, the current submittal must be retracted before submitting the next version.

Proposal:
Provide a spec version drop-down for the user.  When selecting that version, the user can submit to that version of the spec or, retract only that version.

On the certified table display, allow for multiple versions to be displayed in the version column.

Implementation notes:
This will require a DB schema update and some moderate changes to the model and UI.

**Comment by shanecoughlan** [comment]
Sounds like a very useful expansion. Anything I can do to help support as Program Manager?

**Comment by goneall** [comment]
@shanecoughlan Thanks for the offer - It would be great to have an additional contributor or two to help development of the website, so if you know any Java programmers - especially with HTML/CSS/jQuery experience.

It will be a couple months before I get a chance to work on this due to other commitments.  Once implemented, we will want to some testing.  I could really use help testing out the functionality once it has been implemented.

**Comment by shanecoughlan** [comment]
Thanks @goneall. I will put out a call on the main list and see what traction we can get.

**Comment by goneall** [comment]
I will start working on the back-end and analyze any updates required to the model package, dbdao and schema.

**Comment by forakshu** [comment]
Let me know when the back-end updates are done. In the meanwhile i will start getting familiarized with the front-end code.

**Comment by goneall** [comment]
I completed the analysis of the schema and back-end code.  Good news is the database schema does not need to be changed.  I plan on making the following changes to the main Servlet:
- Modify the resetanswers post request - Add a required paramater "specVersion" - should be of the form "x.y", not "x.y.z"
- add a setCurrentSurveyResponse post request with two parameters "specVersion" - should be of the form "x.y", not "x.y.z" and "create" - if true, a new survey response for that version will be created if it does not already exist.  If create is false, the version must be an existing surveyVersion as returned by the getSurveyVersions request
- Add a getSupportedSpecVersions which returns a sorted list of spec versions available in the form "x.y" (does not include the survey version)
- Add a getSurveyVersions which returns a sorted list of spec versions for a user which in the form "x.y" (does not include the survey version)
@forakshu Let me know if the above changes make sense and are sufficient for implementing this feature
Other backend changes would involve changes to the UserSession class and some additional queries being added to the SurveyDbDao and SurveyResponseDao
Implementation is in progress - I'll post an update once I have a pull request ready for review

**Comment by goneall** [comment]
Resolved with PR #10
