### ISSUE TITLE
Update copyright year

### ISSUE THREAD

**Issue by goneall** [OpenChain-Project/Online-Self-Certification-Web-App#94]
Either remove or update the copyright year at the bottom of the index page.

@shanecoughlan  - please comment on your preference to either update the copyright or to remove the date consistent with openchainproject.org website.

**Comment by theopenchainproject** [comment]
Best to update and keep the year to fit into LF convention :)

**Comment by goneall** [comment]
Let's update this after we merge in the i18nrefactor branch.  Should be Monday or Tuesday for the update.

**Comment by goneall** [comment]
Resolve in PR #98
